name: CI Development

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db

        ports:
          - "5432:5432"

        options: >-
          --health-cmd="pg_isready -U postgres -d test_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run lint-check
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          TEST_DB_URL: postgresql://postgres:postgres@localhost:5432/test_db
          USER_POOL_ID: us-east-1_dummyPool1
          COGNITO_CLIENT_ID: dummy-client-id
          AWS_REGION: ${{secrets.AWS_REGION}}
          S3_BUCKET_NAME: ${{secrets.S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

